version: "3.9"

services:
  app:
    build: .
    container_name: gowtham-fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./credentials:/app/credentials
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: gowtham-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
